#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Hollywood.Android.Resource", IsApplication=true)]

namespace Hollywood.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000d
			public const int action_bar_bottom = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int action_bar_top = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int barDarkColor = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int barLightColor = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int barMediumColor = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int black = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int button_bottom = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int button_top = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int listViewBg = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int red = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int sendDarkColor = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int sendLightColor = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int sendMediumColor = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int textColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int textFieldColor = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int textShadow = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int white = 2130968590;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actor = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Apocalypse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Brave = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Clockwork = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DeerHunter = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int down = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Fiction = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GiovanniRibisi = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GriffinDunne = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Heat = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int HughLaurie = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IanHolm = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ItalianJob = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int JaredLeto = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int JasonStatham = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int KateBeckinsale = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MarkWahlberg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MichelleRodriguez = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int movie = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int PaulRudd = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Samurai = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int TopGun = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Trainspotting = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int up = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_ActionBarStyle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
